"""empty message

Revision ID: 8a81c9b04b88
Revises: 5404d99edaa7
Create Date: 2022-05-04 11:29:41.740148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a81c9b04b88'
down_revision = '5404d99edaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'favorite', ['name'], unique=False)
    # ### end Alembic commands ###
